# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0899ce5efcdfa712196f40639af7f0e5fb5c54fba43df3f0a90fc2caeb07919eee70deb55c6e860e0fb5156592eb4c0802e9a5bbb3b1585ac47993919cdc52c0

test:
  secret_key_base: c95abb06a436e09fa7492e2f04a1efea97010d2d3090c272007e77fa2930c3ff2c74d1eb80febf77199e3b0110924bd391bc669cb67536bf4070e03d42c7e4b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
